version: '3.7'
services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'root'
      TZ: Asia/Tokyo
    ports:
      - '3307:3306'
    expose:
      - '3307'
